{
	'name': 'Altek Indent Process Reports',
	'version': '1.0',
	'sequence': 1,
	'author': "Centrics Business Solutions PVT Ltd",
	'website': 'http://www.centrics.cloud/',
	'summary': 'This module contains all the custom reports that related to Indent Process',
	'description': """This module contains all the custom reports that related to Indent Process""",
	'category': 'Tools',
	'depends': ['base', 'sale', 'sale_management', 'altek_indent_process'],
	'external_dependencies': {},
	'data': [
		'security/ir.model.access.csv',
		'wizards/indent_commission_report_detail_view.xml',
		'wizards/indent_commission_receivable_report_view.xml',
		'wizards/indent_commission_individual_performance_report_view.xml',
		'wizards/indent_commission_principle_wise_report_view.xml',
		'wizards/indent_commission_salesperson_wise_report_view.xml',
	],
	'demo': [],
	'installable': True,
	'application': True,
	'auto_install': False,
}
